### ISSUE TITLE
Review of multi-cluster use cases

### ISSUE THREAD

**Issue by font** [onyiny-ang/multi-cluster-use-cases#1]
I reviewed the use cases and I'm capturing some comments here.

- In the [README](https://github.com/onyiny-ang/multi-cluster-use-cases/blob/master/README.md#multi-cluster-use-cases), the Google doc you link to is a private doc.
- What version of k8s is this using? Some of the commands reference version 1.6.4 but we should make this explicit.
- In each of the docs you specify that the persistent volume can be propagated out to each cluster. Can you elaborate on what you mean by that?
- All the specific cluster examples leave out the cluster in the annotations. I know that it specifies you can either leave it out or set it to 0, but I just wanted to confirm again that both worked.
- In the [overall summary](https://github.com/onyiny-ang/multi-cluster-use-cases/blob/master/docs/overall-summary.md), can you elaborate on the last bullet point on what you mean by the DNS connections between clusters need to be set up manually? As stated:
> The ease of declarative application distrubtion may be slightly complicated by adding persistent storage to an app running across a multicluster as DNS connections between clusters need to be set up manually at this time. This issue is out of the scope of this investigation.
- It would be useful to capture how to deploy an entire application beyond just nginx, such as all the microservice components of a namespace that make up an application. Basically, just demonstrating how to handle deploying a multi-tiered application using one kubectl command.

I think this investigation suffices to capture the way to handle these 4 use-cases using k8s federation in the simplest way. However, for more complicated cases, there are likely some unexpected behaviors. If we want to capture any existing bugs with k8s federation as a result of trying to handle these use cases, I'd suggest the following:
- We should capture what happens for these use cases when deploying the FCP and joining clusters after you've manually deployed your application onto multiple k8s clusters that were not federated. In theory, it should still work as expected. But this piece is critical because users do not necessarily know they want to federate their clusters before deploying their application onto multiple clusters. In other words, this would make or break using the FCP.
- In your testing of nginx, were you able to confirm which cluster was responding or that the DNS entries all looked correct? For example, it would be interesting to test with an application that is "cloud" aware, such as pacman, to confirm you're talking to the cluster you expect based on the DNS entries.
- What happens when deploying the FCP to manage multiple clusters spread across different cloud providers such as GKE, AWS, and Azure? How, if at all, are these use cases impacted?

**Comment by onyiny-ang** [comment]
> In the README, the Google doc you link to is a private doc.

Removed

> What version of k8s is this using? Some of the commands reference version 1.6.4 but we should make this explicit.

Fixed: https://github.com/onyiny-ang/multi-cluster-use-cases/blob/master/README.md#L22

> In each of the docs you specify that the persistent volume can be propagated out to each cluster. Can you elaborate on what you mean by that?

It took me a long time to remember what I meant by that. I was confused about how PVC worked at the time. I'm still not 100% sure that what I've changed it to is correctly articulated, but I think it's closer to the truth at least, now.: https://github.com/onyiny-ang/multi-cluster-use-cases/blob/master/docs/cdac-summary.md#L38-#L39

> All the specific cluster examples leave out the cluster in the annotations. I know that it specifies you can either leave it out or set it to 0, but I just wanted to confirm again that both worked.

Yes, I tested both and they both worked. I have added a note about this in the overall summary. https://github.com/onyiny-ang/multi-cluster-use-cases/blob/master/docs/overall-summary.md

> In  the overall summary, can you elaborate on the last bullet point on what you mean by the DNS connections between clusters need to be set up manually? 

Updated:https://github.com/onyiny-ang/multi-cluster-use-cases/blob/master/docs/overall-summary.md

> It would be useful to capture how to deploy an entire application beyond just nginx, such as all the microservice components of a namespace that make up an application. Basically, just demonstrating how to handle deploying a multi-tiered application using one kubectl command.

Noted. I could maybe do a case study of pacman going through all the different use-cases.

> We should capture what happens for these use cases when deploying the FCP and joining clusters after you've manually deployed your application onto multiple k8s clusters that were not federated. In theory, it should still work as expected. But this piece is critical because users do not necessarily know they want to federate their clusters before deploying their application onto multiple clusters. In other words, this would make or break using the FCP.

For the experiments that I tested here, adding a new cluster to the FCP after the fact, when nginx was already deployed, had no noticeable negative impacts on the application/FCP. I was able to scale up to the newly joined cluster, leaving other clusters out or just redistributing replicas across all clusters. I didn't test what happens if the host cluster is removed after deployment. I would suspect that would cause issues. If an application is already deployed on a cluster that is then added to the FCP, any namespaces within that cluster that are also present in the FCP will be overwritten to reflect the specs in the FCP. Any namespaces within a cluster that are not present in the FCP will remain unchanged. I have added a note about this in the overall summary

> In your testing of nginx, were you able to confirm which cluster was responding or that the DNS entries all looked correct? For example, it would be interesting to test with an application that is "cloud" aware, such as pacman, to confirm you're talking to the cluster you expect based on the DNS entries.

Checked.

> What happens when deploying the FCP to manage multiple clusters spread across different cloud providers such as GKE, AWS, and Azure? How, if at all, are these use cases impacted?

Testing now. Will report.

**Comment by onyiny-ang** [comment]
Updated the overall summary to say that testing was performed with both GKE and AWS clusters. There were no strange bugs found to inhibit AWS from working the same way as was found with GKE. Of course, that is still assuming that GKE is being used for the FCP.

**Comment by onyiny-ang** [comment]
>> We should capture what happens for these use cases when deploying the FCP and joining clusters after you've manually deployed your application onto multiple k8s clusters that were not federated. In theory, it should still work as expected. But this piece is critical because users do not necessarily know they want to federate their clusters before deploying their application onto multiple clusters. In other words, this would make or break using the FCP.

>For the experiments that I tested here, adding a new cluster to the FCP after the fact, when nginx was already deployed, had no noticeable negative impacts on the application/FCP. I was able to scale up to the newly joined cluster, leaving other clusters out or just redistributing replicas across all clusters. I didn't test what happens if the host cluster is removed after deployment. I would suspect that would cause issues. If an application is already deployed on a cluster that is then added to the FCP, any namespaces within that cluster that are also present in the FCP will be overwritten to reflect the specs in the FCP. Any namespaces within a cluster that are not present in the FCP will remain unchanged. I have added a note about this in the overall summary

To more fully answer this question I deployed an application in a specific namespace on 1 GKE and 1 AWS cluster before joining them to the FCP. Upon joining them to the FCP, they remain in whatever namespace/state they were created with(in). IF a deployment with the same namespace is made in the FCP, that namespace within each cluster will be overwritten by whatever is communicated to the FCP. re deploying their application onto multiple clusters. In other words, this would make or break using the FCP.

If the host cluster is removed from the FCP after deployment it doesn't make a difference as the host cluster does not, itself, need to be joined to the FCP for the FCP to function properly.
